"""DOCX exporter: one Word document with a heading section per source file."""
from __future__ import annotations

from pathlib import Path

from ..models import FileResult, TranscribeOptions
from ._shared import format_timestamp, language_label


def export_docx(results: list[FileResult], options: TranscribeOptions, dst: Path) -> Path:
    from docx import Document
    from docx.shared import Pt

    doc = Document()
    doc.add_heading("Transcript", level=0)
    doc.add_paragraph().add_run("Generated by Timbre").italic = True

    toc = doc.add_paragraph()
    toc.add_run("Contents").bold = True
    for index, result in enumerate(results, start=1):
        doc.add_paragraph(f"{index}. {result.filename}", style="List Number")

    for index, result in enumerate(results, start=1):
        doc.add_heading(f"{index}. {result.filename}", level=1)
        meta = doc.add_paragraph()
        meta.add_run(
            f"Language: {language_label(result)}  |  "
            f"Duration: {format_timestamp(result.duration)}"
        ).font.size = Pt(9)

        if options.include_timestamps:
            for seg in result.segments:
                para = doc.add_paragraph()
                stamp = para.add_run(f"[{format_timestamp(seg.start)}] ")
                stamp.bold = True
                para.add_run(seg.text.strip())
        else:
            doc.add_paragraph(result.text)

    dst.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(dst))
    return dst
