"""Markdown exporter: one combined file with a heading per source file."""
from __future__ import annotations

from pathlib import Path

from ..models import FileResult, TranscribeOptions
from ._shared import format_timestamp, language_label


def export_markdown(results: list[FileResult], options: TranscribeOptions, dst: Path) -> Path:
    lines: list[str] = []
    lines.append("# Transcript")
    lines.append("")
    lines.append("_Generated by [Timbre](https://github.com/dpaguba/timbre)._")
    lines.append("")
    lines.append("## Contents")
    lines.append("")
    for index, result in enumerate(results, start=1):
        anchor = _anchor(result.filename, index)
        lines.append(f"{index}. [{result.filename}](#{anchor})")
    lines.append("")

    for index, result in enumerate(results, start=1):
        lines.append(f"## {index}. {result.filename}")
        lines.append("")
        lines.append(
            f"**Language:** {language_label(result)}  \n"
            f"**Duration:** {format_timestamp(result.duration)}"
        )
        lines.append("")
        if options.include_timestamps:
            for seg in result.segments:
                lines.append(f"- `{format_timestamp(seg.start)}` {seg.text.strip()}")
        else:
            lines.append(result.text)
        lines.append("")

    dst.write_text("\n".join(lines), encoding="utf-8")
    return dst


def _anchor(filename: str, index: int) -> str:
    """Build the heading anchor the way GitHub and CommonMark renderers do.

    They lowercase, drop punctuation, keep underscores and hyphens, and turn
    spaces into hyphens. Mapping every non-alphanumeric character to a hyphen
    instead produced `#1-interview-en-mp3` for `interview_en.mp3`, so every
    entry in the table of contents pointed at nothing, since every filename
    carries an extension.
    """
    slug_chars = []
    for char in filename.lower():
        if char.isalnum() or char in "_-":
            slug_chars.append(char)
        elif char.isspace():
            slug_chars.append("-")
    slug = "".join(slug_chars).strip("-")
    return f"{index}-{slug}"
