"""Plain-text exporter: one combined file, a section per source file."""
from __future__ import annotations

from pathlib import Path

from ..models import FileResult, TranscribeOptions
from ._shared import format_timestamp, language_label


def export_txt(results: list[FileResult], options: TranscribeOptions, dst: Path) -> Path:
    lines: list[str] = []
    lines.append("TRANSCRIPT")
    lines.append("Generated by Timbre")
    lines.append("=" * 60)
    lines.append("")

    for index, result in enumerate(results, start=1):
        lines.append(f"[{index}] {result.filename}")
        lines.append(f"Language: {language_label(result)}  |  Duration: {format_timestamp(result.duration)}")
        lines.append("-" * 60)
        if options.include_timestamps:
            for seg in result.segments:
                lines.append(f"[{format_timestamp(seg.start)}] {seg.text.strip()}")
        else:
            lines.append(result.text)
        lines.append("")
        lines.append("")

    dst.write_text("\n".join(lines), encoding="utf-8")
    return dst
